Unify addsite/delsite validation logic/messages

diff --git a/addsite b/addsite
--- a/addsite
+++ b/addsite
@@ -5,6 +5,16 @@ case "$1" in
         shift 2
 esac
 
+if [[
+    -z "$1" ||
+    "$1" != "$(basename "$1")" ||
+    "." = "$1" ||
+    ".." = "$1" ||
+]]; then
+    >&2 echo "Invalid site '$1' offered, aborting"
+    exit 1
+fi
+
 if [[ -d "$HOME/localhost/$1" ]]; then
     >&2 echo "'$HOME/localhost/$1' already exists, aborting."
     exit 1
diff --git a/delsite b/delsite
--- a/delsite
+++ b/delsite
@@ -6,7 +6,7 @@ if [[
     ".." = "$1" ||
     ! -d "$HOME/localhost/$1"
 ]]; then
-    >&2 echo "No site offered, aborting"
+    >&2 echo "Invalid site '$1' offered, aborting"
     exit 1
 fi
 
